# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
      # This pipeline will be extended to the OneESPT template
trigger: none
name: $(Date:yyyyMMdd).$(Rev:r)
resources:
  pipelines:
  - pipeline: 'SBOMTool'
    project: 'AzureDevOps'
    source: 'SSSC\SBOM Tool\SBOM Tool Main Build (YAML)'
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    settings:
      networkIsolationPolicy: Permissive
    pool:
      name: sbom-windows-build-pool
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling-Release
    stages:
    - stage: Stage_1
      displayName: Validate Drop
      jobs:
      - job: Job_1
        displayName: Validate Windows Manifest
        condition: succeeded()
        timeoutInMinutes: 0
        templateContext:
          inputs:
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-GitHub-macOS'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-GitHub-macOS'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-macOS'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-macOS'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-GitHub-macOS-arm64'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-GitHub-macOS-arm64'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-macOS-arm64'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-macOS-arm64'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-GitHub-linux'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-GitHub-linux'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-linux'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-linux'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-GitHub'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-GitHub'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool'
        steps:
        - task: AzureArtifacts.drop-validator-task.drop-validator-task.DropValidatorTask@0
          displayName: 'Drop Validator '
          inputs:
            BuildDropPath: $(System.DefaultWorkingDirectory)/SBOMTool
            ManifestDirPath: $(System.DefaultWorkingDirectory)/SBOMTool/_manifest
            OutputPath: $(System.DefaultWorkingDirectory)/SBOMTool/bin/win-x64-validation-output.json
            ValidateSignature: false
            Verbosity: Verbose
      - job: Job_2
        displayName: Validate Linux Manifest
        condition: succeeded()
        timeoutInMinutes: 0
        templateContext:
          inputs:
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-GitHub-macOS'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-GitHub-macOS'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-macOS'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-macOS'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-GitHub-macOS-arm64'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-GitHub-macOS-arm64'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-macOS-arm64'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-macOS-arm64'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-GitHub-linux'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-GitHub-linux'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-linux'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-linux'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-GitHub'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-GitHub'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool'
        steps:
        - task: AzureArtifacts.drop-validator-task.drop-validator-task.DropValidatorTask@0
          displayName: 'Drop Validator '
          inputs:
            BuildDropPath: $(System.DefaultWorkingDirectory)/SBOMTool-linux
            ManifestDirPath: $(System.DefaultWorkingDirectory)/SBOMTool-linux/_manifest
            OutputPath: $(System.DefaultWorkingDirectory)/SBOMTool-linux/bin/linux-x64-validation-output.json
            ValidateSignature: false
      - job: Job_3
        displayName: Validate OSX Manifest
        condition: succeeded()
        timeoutInMinutes: 0
        templateContext:
          inputs:
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-GitHub-macOS'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-GitHub-macOS'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-macOS'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-macOS'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-GitHub-macOS-arm64'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-GitHub-macOS-arm64'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-macOS-arm64'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-macOS-arm64'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-GitHub-linux'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-GitHub-linux'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-linux'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-linux'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-GitHub'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-GitHub'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool'
        steps:
        - task: AzureArtifacts.drop-validator-task.drop-validator-task.DropValidatorTask@0
          displayName: 'Drop Validator '
          inputs:
            BuildDropPath: $(System.DefaultWorkingDirectory)/SBOMTool-macOS
            ManifestDirPath: $(System.DefaultWorkingDirectory)/SBOMTool-macOS/_manifest
            OutputPath: $(System.DefaultWorkingDirectory)/SBOMTool-macOS/bin/osx-x64-validation-output.json
            ValidateSignature: false
    - stage: Stage_2
      displayName: Push NuGet (private feeds)
      dependsOn: Stage_1
      jobs:
      - job: PreDeploymentApprovalJob
        displayName: Pre-Deployment Approval
        condition: succeeded()
        timeoutInMinutes: 0
        pool: server
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: |-
              [TEAM FOUNDATION]\Code Sharing RM MGRS,
              [1ES]\SBOM,
              [1ES]\SBOM-EBOM
            approvers: |-
              [TEAM FOUNDATION]\Code Sharing RM MGRS,
              [1ES]\SBOM,
              [1ES]\SBOM-EBOM
      - job: Job_1
        displayName: Push packages to ManifestTool feed
        dependsOn: PreDeploymentApprovalJob
        condition: succeeded()
        timeoutInMinutes: 0
        templateContext:
          inputs:
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-GitHub-macOS'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-GitHub-macOS'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-macOS'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-macOS'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-GitHub-macOS-arm64'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-GitHub-macOS-arm64'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-macOS-arm64'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-macOS-arm64'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-GitHub-linux'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-GitHub-linux'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-linux'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-linux'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-GitHub'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-GitHub'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool'
        steps:
        - task: NuGetAuthenticate@1
          displayName: NuGet Authenticate
        - task: 1ES.PublishNuGet@1
          displayName: 'Push packages to ManifestTool feed'
          inputs:
            packageParentPath: '$(System.DefaultWorkingDirectory)/SBOMTool/nuget'
            verbosityRestore: Detailed
            packagesToPush: $(System.DefaultWorkingDirectory)/SBOMTool/nuget/*.nupkg
            publishVstsFeed: AzureDevOps/ManifestTool
            allowPackageConflicts: $(AllowPackageConflicts)
    - stage: Stage_3
      displayName: GitHub Release
      dependsOn: Stage_2
      jobs:
      - job: PreDeploymentApprovalJob
        displayName: Pre-Deployment Approval
        condition: succeeded()
        timeoutInMinutes: 0
        pool: server
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: |-
              [TEAM FOUNDATION]\Code Sharing RM MGRS,
              [1ES]\SBOM,
              [1ES]\SBOM-EBOM
            approvers: |-
              [TEAM FOUNDATION]\Code Sharing RM MGRS,
              [1ES]\SBOM,
              [1ES]\SBOM-EBOM
      - job: Job_1
        displayName: Release on GitHub
        dependsOn: PreDeploymentApprovalJob
        condition: succeeded()
        timeoutInMinutes: 0
        templateContext:
          type: releaseJob
          isProduction: true
          inputs:
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-GitHub-macOS'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-GitHub-macOS'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-macOS'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-macOS'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-GitHub-macOS-arm64'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-GitHub-macOS-arm64'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-macOS-arm64'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-macOS-arm64'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-GitHub-linux'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-GitHub-linux'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-linux'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-linux'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-GitHub'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-GitHub'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool'
        steps:
        - task: PowerShell@2
          name: SBOMToolVersion
          displayName: Get current tag version
          inputs:
            targetType: inline
            script: |-
              $version = Get-Content -Path $(System.DefaultWorkingDirectory)\SBOMTool\version.txt
              echo "##vso[task.setvariable variable=Version;isOutput=true]v$version"
        - task: PowerShell@2
          displayName: Rename manifests
          inputs:
            targetType: inline
            script: |-
              Rename-Item -Path "$(System.DefaultWorkingDirectory)/SBOMTool-GitHub-macOS/_manifest/spdx_2.2/manifest.spdx.json" -NewName "osx-x64-manifest.spdx.json"
              Rename-Item -Path "$(System.DefaultWorkingDirectory)/SBOMTool-GitHub-macOS-arm64/_manifest/spdx_2.2/manifest.spdx.json" -NewName "osx-arm64-manifest.spdx.json"
              Rename-Item -Path "$(System.DefaultWorkingDirectory)/SBOMTool-GitHub-linux/_manifest/spdx_2.2/manifest.spdx.json" -NewName "linux-x64-manifest.spdx.json"
              Rename-Item -Path "$(System.DefaultWorkingDirectory)/SBOMTool-GitHub/_manifest/spdx_2.2/manifest.spdx.json" -NewName "win-x64-manifest.spdx.json"
        - task: GitHubRelease@1
          displayName: Upload assets to GitHub Release
          inputs:
            gitHubConnection: SBOM GitHub
            action: edit
            tag: $(SBOMToolVersion.Version)
            releaseNotesSource: inline
            assets: |-
              $(System.DefaultWorkingDirectory)\**\bin\**
              $(System.DefaultWorkingDirectory)\**\SBOMTool-GitHub*\\**\*-manifest.spdx.json
            assetUploadMode: replace
            isDraft: true
            addChangeLog: false
    - stage: Stage_4
      displayName: Push to NuGet.org
      dependsOn: Stage_2
      jobs:
      - job: PreDeploymentApprovalJob
        displayName: Pre-Deployment Approval
        condition: succeeded()
        timeoutInMinutes: 0
        pool: server
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: |-
              [TEAM FOUNDATION]\Code Sharing RM MGRS,
              [1ES]\SBOM,
              [1ES]\SBOM-EBOM
            approvers: |-
              [TEAM FOUNDATION]\Code Sharing RM MGRS,
              [1ES]\SBOM,
              [1ES]\SBOM-EBOM
      - job: Job_1
        displayName: Push to NuGet.org
        dependsOn: PreDeploymentApprovalJob
        condition: succeeded()
        timeoutInMinutes: 0
        templateContext:
          inputs:
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-GitHub-macOS'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-GitHub-macOS'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-macOS'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-macOS'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-GitHub-macOS-arm64'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-GitHub-macOS-arm64'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-macOS-arm64'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-macOS-arm64'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-GitHub-linux'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-GitHub-linux'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-linux'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-linux'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool-GitHub'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool-GitHub'
            - input: pipelineArtifact
              pipeline: 'SBOMTool'
              artifactName: 'SBOMTool'
              targetPath: '$(System.DefaultWorkingDirectory)/SBOMTool'
        steps:
        - task: UseDotNet@2
          displayName: Use .NET Core
        - task: PowerShell@2
          displayName: Push packages to NuGet.org
          inputs:
            targetType: inline
            script: |
              dotnet nuget push "$(System.DefaultWorkingDirectory)\SBOMTool\nuget\*.nupkg" -s https://api.nuget.org/v3/index.json -k $(NuGetApiKey)
