name: Test comments if targeted files are touched

on:
  pull_request:
    types:
      - opened
    paths:
      - 'src/**'
      
jobs:
  auto-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: PR Comment
        run:
          gh pr comment $PRNUM "This is just a test"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PRNUM: ${{ github.event.pull_request.number }}