name: Test comments if targeted files are touched

on:
  pull_request:
    paths:
      - 'src/Microsoft.Sbom.Api/**/*'
      
jobs:
  auto-comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: PR Comment
        run:
          gh pr comment $PRNUM -b "You touched the API project--how does this impact the API version?"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PRNUM: ${{ github.event.pull_request.number }}